# -*- coding: utf-8 -*-
"""
Build the static (no-Python) version of MovieFlix into docs/.

    python tools/build_static.py

It reads the same dataset the Flask app uses, precomputes every
recommendation with the same TF-IDF model, and writes everything the browser
needs as plain files:

    docs/data.js      movie catalogue + precomputed recommendations
    docs/style.css    copied from static/css/style.css
    docs/posters/     copied from static/posters/

The data is written as a .js file rather than .json on purpose: a page opened
straight from disk (file://) is not allowed to fetch() a local .json, but it
can always load a <script>. So docs/index.html works by double-clicking it,
on GitHub Pages, or on any web host.
"""

import json
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import recommendation as R  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")

TOP_N = 8


def build_data():
    """movies + precomputed recommendations, exactly as the Flask app ranks them."""
    movies = R.get_all_movies()

    catalogue = [
        {
            "id": m["id"],
            "title": m["title"],
            "genre": m["genre"],
            "description": m["description"],
            "rating": round(float(m["rating"]), 1),
            "year": int(m["year"]),
            # stored relative to docs/, e.g. "posters/inception.jpg"
            "poster": m["poster"],
            "trailer": m["trailer"],
        }
        for m in movies
    ]

    similar = {}
    for movie in movies:
        similar[movie["id"]] = [
            [item["id"], item["match"]]
            for item in R.recommend_movies(movie["title"], TOP_N)
        ]

    return catalogue, similar, R.get_genres()


def write_data_js(catalogue, similar, genres):
    path = os.path.join(DOCS, "data.js")

    dump = lambda value: json.dumps(value, separators=(",", ":"), ensure_ascii=False)

    with open(path, "w", encoding="utf-8") as handle:
        handle.write("/* Generated by tools/build_static.py - do not edit by hand. */\n")
        handle.write("/* Rebuild with: python tools/build_static.py            */\n\n")
        handle.write("const MOVIES = " + dump(catalogue) + ";\n\n")
        handle.write("const SIMILAR = " + dump(similar) + ";\n\n")
        handle.write("const GENRES = " + dump(genres) + ";\n")

    return os.path.getsize(path)


def copy_assets():
    # stylesheet — the static site reuses the exact same one as the Flask app
    source_css = os.path.join(ROOT, "static", "css", "style.css")
    shutil.copyfile(source_css, os.path.join(DOCS, "style.css"))

    # posters
    source_posters = os.path.join(ROOT, "static", "posters")
    target_posters = os.path.join(DOCS, "posters")
    os.makedirs(target_posters, exist_ok=True)

    copied = 0
    for name in os.listdir(source_posters):
        source = os.path.join(source_posters, name)
        target = os.path.join(target_posters, name)
        if not os.path.exists(target) or os.path.getmtime(source) > os.path.getmtime(target):
            shutil.copyfile(source, target)
        copied += 1

    # drop posters that no longer exist in the dataset
    for name in os.listdir(target_posters):
        if not os.path.exists(os.path.join(source_posters, name)):
            os.remove(os.path.join(target_posters, name))

    return copied


def main():
    if not os.path.isdir(DOCS):
        os.makedirs(DOCS)

    catalogue, similar, genres = build_data()
    size = write_data_js(catalogue, similar, genres)
    posters = copy_assets()

    missing = [m["title"] for m in catalogue if not m["poster"]]
    no_trailer = [m["title"] for m in catalogue if not m["trailer"]]

    print(f"  movies            : {len(catalogue)}")
    print(f"  genres            : {len(genres)}")
    print(f"  recommendations   : {sum(len(v) for v in similar.values())} pairs")
    print(f"  data.js           : {size / 1024:.1f} KB")
    print(f"  posters copied    : {posters}")
    print(f"  missing posters   : {missing or 'none'}")
    print(f"  missing trailers  : {no_trailer or 'none'}")
    print()
    print(f"  Static site ready in {DOCS}")
    print("  Open docs/index.html directly, or publish it with GitHub Pages.")


if __name__ == "__main__":
    main()
